version: "3"

services:
  natours_db:
    container_name: natours_db
    image: mohamedsalama118/mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/natours:/data/db

  #node api services
  api:
    build: ./app
    ports:
      - 80:3000
    volumes:
      - ./app/src:/app/src
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE: mongodb://natours_db:27017/natours
      DATABASE_PASSWORD: 3032000
      EXPIRES_IN: 90d
      JWT_COOKIE_EXPIRES_IN: 90
      JWT_SECRET: MY-JWT_SECRET-for-nodejs-and-express-and-mongodb
      EMAIL_USERNAME: 7a1c4978319beb
      EMAIL_PASSWORD: 840db2be3280c1
      EMAIL_HOST: smtp.mailtrap.io
      EMAIL_PORT: 2525
    depends_on:
      - natours_db
